### ISSUE TITLE
Unable to start mapCreator

### ISSUE THREAD

**Issue by kavindajd** [sjev/mapCreator#1]
Set up the settings.ini file but I receive this error:

![error](https://cloud.githubusercontent.com/assets/12617585/7824549/a818aafe-03fb-11e5-9061-7cddf7fab45a.png)

Any suggestions?

Here's what my settings.ini file looks like. I had to comment out [venlo]:

> get bounding box from http://www.oche.de/~junker/OSM/bbox-tool/bbox.html
> placeholders {0} = zoom, {1}= x, {2} = y
> [venlo]
> source = http://a.tile.openstreetmap.org/{0}/{1}/{2}.png
> dest = C:\maps
> tilestore = C:\data\tilestore
> zoom = 14
> bbox = <bbox e="-82.385" n="27.932" s="27.782" w="-82.613"/>

**Comment by sjev** [comment]
It looks like you messed up your .ini file as the parser can not find section headers. 
Commenting out '[Venlo]' removes a section header, so that is most probably the cause.

**Comment by kavindajd** [comment]
Thanks sjev, but after I correct the header and run again, I get this:

> Traceback (most recent call last):
>   File "mapcreator.py", line 28, in <module>
>     source =  p.get(name,'source')
>   File "C:\Python27\lib\ConfigParser.py", line 607, in get
>     raise NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'Map'

I'm sure that the link to OSM tile servers is correct...

**Comment by sjev** [comment]
This is not a MapCreator issue, but rather a user providing wrong input which ConfigParser module can not parse.
